spring:
  config:
    activate:
      on-profile: secret
  datasource:
    username: postgres
    password: hellorain78!
    url: jdbc:postgresql://esl.ctmkkocyo18y.ap-northeast-2.rds.amazonaws.com:5432/esl
    driver-class-name: org.postgresql.Driver